import Head from 'next/head'

import Sidebar from '../components/Sidebar'




export default function Home() {
  return (
    <>
      <Head>
        <title>twitter-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://help.twitter.com/content/dam/help-twitter/brand/logo.png" />
      </Head>

    <main>
        {/* SideBar */}
        <Sidebar/>

        {/* Feed */}
  
        {/* Widgets */}
  
        {/* Modal */}
    </main>
     
    </>
  )
}
